# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: 'chore'
    labels:
      - chore
      - dependencies
    groups:
      security:
        applies-to: security-updates
        patterns:
          - '*'
      minor_patch:
        update-types:
          - minor
          - patch
      major:
        update-types:
          - major
      pre_release:
        patterns:
          - '*'

