name: Registry Publish

on:
  workflow_run:
    workflows:
      - Bundle and Deploy
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  registry-publish:
    name: Registry Publish
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Registry Publish
        run: |
          gh api \
            --method POST \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            /repos/paperback-community/extensions/dispatches \
            -f 'event_type=registry-publish' \
            -F "client_payload[repository]=${{ github.repository }}" \
            -F "client_payload[branch]=${{ github.ref_name }}"
